// @ts-nocheck
// eslint-disable
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/@bracketed/vite-plugin-router
// https://github.com/bracketed/vite-router

import type { Props } from '@bracketed/vite-plugin-router/types';
import { lazy } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';

const R1 = lazy(() => import('./pages/'));

/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/@bracketed/vite-plugin-router
 * @link https://github.com/bracketed/vite-router
 */
export function AppRoutes(props: Props) {
	return (
		<BrowserRouter>
			<Routes>
				<Route
					path={'/*'}
					key={'/*'}
					element={
						<R1 Location={'Home'} Description={'Home page of the website.'}></R1>
					}></Route>
			</Routes>
		</BrowserRouter>
	);
}

